### ISSUE TITLE
Verdaccio 搭建私有 npm 仓库

### ISSUE THREAD

**Issue by keyding** [b1g3rr0r/record#8]
## 私有 `npm` 仓库的好处

- 公司内部开发的私有的包，仅想在内部使用，并且不想使用`git + ssh`的方式
- `npm` 上下载包很慢，想要把安装过的包缓存起来，下一次安装的时候，先检查更新，如果没更新，从缓存下载
- `npm` 安装包时，私有包从私有仓库下载，公共包从 `npm` 仓库下载

## 搭建方式

- sinopia(不推荐，已经不维护)
- Verdaccio(推荐，简单)
- cnpm(推荐，复杂)

### Verdaccio

[Verdaccio 中文文档](https://verdaccio.org/zh-CN/)

 一个轻量的私有 `npm proxy registry`，是 `sinopia` 开源框架的一个分支，另外 `sinopia` 现在已经没人维护了。

#### verdaccio 全局安装

```bash
npm install --global verdaccio
# or
yarn global add verdaccio
```

#### 运行 verdaccio

```bash
verdaccio

# warn --- config file  - /xxx/.config/verdaccio/config.yaml
# warn --- Plugin successfully loaded: htpasswd
# warn --- Plugin successfully loaded: audit
# warn --- http address - http://localhost:4873/ - verdaccio/3.12.0
```
成功运行，浏览器打开 `http://localhost:4873` 可以正常看到页面。

#### 通过 `pm2` 持久化运行

全局安装 `pm2` 

```bash
npm install -g pm2
# or
yarn global add pm2
```

运行

```bash
pm2 start verdaccio

[PM2] Applying action restartProcessId on app [verdaccio](ids: [ 0 ])
[PM2] [verdaccio](0) ✓
[PM2] Process successfully started
┌───────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name  │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├───────────┼────┼─────────┼──────┼─────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ verdaccio │ 0  │ N/A     │ fork │ 513 │ online │ 0       │ 0s     │ 0%  │ 20.7 MB   │ root │ disabled │
└───────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```
[pm2 中文文档](https://pm2.io/doc/zh/runtime/overview/)

#### 默认配置项说明

` /xxx/.config/verdaccio/config.yaml` 默认的配置文件，4873 为默认端口，也可以修改默认配置。

[Verdaccio 配置选项说明](https://verdaccio.org/docs/zh-CN/configuration)

```yaml
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
# 所有包的缓存目录
storage: ./storage

# path to a directory with plugins to include
# 插件目录
plugins: ./plugins

# WebUI 配置
web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  # enable: false
  title: Verdaccio

# 验证信息
auth:
  htpasswd:
    # 存储用户信息
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    # 可通过设置 max_users: -1 来禁用注册用户
    # max_users: 1000

# a list of other known repositories we can talk to
# 公共仓库配置
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    # 允许所有用户(包括未验证身份的用户)读取和发布所有包
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    # 可以通过用户分组或用户名来控制访问权限
    # $all 所有人 $anonymous 匿名用户 $认证(登录)用户
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    # 允许登录用户发布包
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    # 代理，表示如果本地没有，就向此代理服务器发起请求
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incomming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enought.
server:
  keepAliveTimeout: 60

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true
    
# 监听端口，不配置默认只能本机访问
listen: 0.0.0.0:4873

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
```

### 本地配置 `npm` 源

```bash
# 当前npm源指向私有仓库
npm set registry http://localhost:4873
```
或推荐使用 `nrm` 来管理源

#### 全局安装 `nrm`

```bash
npm install -g nrm
# or
yarn global add nrm
```

#### `nrm` 查看源列表

```bash
nrm ls

#  npm ---- https://registry.npmjs.org/
#* cnpm --- http://r.cnpmjs.org/
#  taobao - https://registry.npm.taobao.org/
#  nj ----- https://registry.nodejitsu.com/
#  npmMirror  https://skimdb.npmjs.com/registry/
#  edunpm - http://registry.enpmjs.org/
```

`*` 表示的为当前使用的源

#### 切换源

```bash
nrm use cnpm

# Registry has been set to: http://r.cnpmjs.org/
```

#### 添加私有仓库源

```bash
# 添加
nrm add local_npm http://localhost:4873

# 切换
nrm use local_npm 
```

### 注册用户

```bash
# 先检查并切换至私有仓库源
nrm use local_npm

# 注册用户
npm adduser

# Username: test-user
# Password:
# Email: (this IS public) test-user@xxx.com
# Logged in as test-user on http://localhost:4873/.
```

按提示输入Username、Password 和 Email 即可注册完成。

### 登录用户

```bash
npm login

# Username: test-user
# Password:
# Email: (this IS public)  test-user@xxx.com
# Logged in as  test-user on http://localhost:4873/.
```

输入刚注册时的 Username、Password 和 Email。

### 查看用户登录是否成功

```bash
npm who am i

# test-user
```

### 发布包

```bash
npm publish

# npm notice
# npm notice 📦  kuyun-ui@0.0.13
# npm notice === Tarball Contents ===
# npm notice 809B    package.json
# ... ...
# npm notice === Tarball Details ===
# npm notice name:          test-npm-lab
# npm notice version:       0.0.1
# npm notice package size:  1.9 MB
# npm notice unpacked size: 7.9 MB
# npm notice shasum:        45848464cfa85c019f38f61a[xxx]2beb3b5475500
# npm notice integrity:     sha512-UCT4t9q07cM1w[...]EGgAyTrzgC3dA==
# npm notice total files:   3
# npm notice
# + test-npm-lab@0.0.1
```

发布成功，此时，可通过 webui 查看详细信息。

### 安装包

```bash
# 切换至私有仓库源
nrm use local_npm

# 安装包
npm install test-npm-lab
```

如果私有仓库中不包含你要安装的包，会从代理的npmjs去下载，并且会缓存在 `./storage` 文件夹下，再次下载会先检查包是否有更新，无更新直接从缓存下载。
